# Generated by Django 5.0.1 on 2026-07-19 11:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del rol')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('puede_gestionar_usuarios', models.BooleanField(default=False)),
                ('puede_gestionar_productos', models.BooleanField(default=False)),
                ('puede_ventas', models.BooleanField(default=False)),
                ('puede_auditoria', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Apellidos')),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('NIE', 'NIE'), ('PASS', 'Pasaporte')], default='DNI', max_length=5)),
                ('numero_documento', models.CharField(blank=True, max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='usuarios/')),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='2FA activado')),
                ('two_factor_code', models.CharField(blank=True, max_length=6)),
                ('two_factor_expiry', models.DateTimeField(blank=True, null=True)),
                ('intentos_fallidos', models.PositiveSmallIntegerField(default=0)),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True)),
                ('debe_cambiar_password', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='farmacia.rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accion', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGIN_FAIL', 'Intento de login fallido'), ('LOGOUT', 'Cierre de sesión'), ('REGISTRO', 'Registro de usuario'), ('2FA', 'Verificación 2FA'), ('CREATE', 'Creación'), ('UPDATE', 'Modificación'), ('DELETE', 'Eliminación'), ('VIEW', 'Consulta'), ('EXPORT', 'Exportación'), ('OTRO', 'Otro')], max_length=15)),
                ('modelo', models.CharField(blank=True, max_length=60)),
                ('objeto_id', models.CharField(blank=True, max_length=60)),
                ('descripcion', models.TextField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('datos', models.JSONField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Auditoría',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['-fecha'], name='farmacia_au_fecha_dc7ce0_idx'), models.Index(fields=['accion'], name='farmacia_au_accion_aecfe2_idx'), models.Index(fields=['usuario'], name='farmacia_au_usuario_19a040_idx')],
            },
        ),
    ]
