# Generated by Django 5.0.1 on 2026-07-19 12:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0002_categoria_proveedor_producto_movimientostock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('puesto', models.CharField(choices=[('FARM', 'Farmacéutico'), ('TEC', 'Técnico en farmacia'), ('CAJ', 'Cajero'), ('ADM', 'Administración')], default='FARM', max_length=4)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('fecha_alta', models.DateField(default=django.utils.timezone.now)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Fichaje',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('salida', models.DateTimeField(blank=True, null=True)),
                ('nota', models.CharField(blank=True, max_length=160)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichajes', to='farmacia.empleado')),
            ],
            options={
                'verbose_name': 'Fichaje',
                'verbose_name_plural': 'Fichajes',
                'ordering': ['-entrada'],
            },
        ),
    ]
