# Generated by Django 5.0.1 on 2026-07-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0004_venta_detalleventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cliente_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
