# Generated by Django 5.0.1 on 2026-07-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0005_venta_cliente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='usuario',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
