# Generated by Django 5.0.1 on 2026-07-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0006_usuario_token_usuario_token_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cn',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código Nacional (CIMA)'),
        ),
    ]
