# Generated by Django 5.0.1 on 2026-07-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0007_producto_cn'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto_url',
            field=models.URLField(blank=True, verbose_name='URL foto (CIMA)'),
        ),
    ]
