# Generated by Django 5.0.1 on 2026-07-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0008_producto_foto_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('alergias', models.TextField(blank=True, verbose_name='Alergias / observaciones')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
    ]
