# Generated by Django 5.0.1 on 2026-07-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0009_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='puntos',
            field=models.IntegerField(default=0, verbose_name='Puntos de fidelización'),
        ),
    ]
