# Generated by Django 5.0.1 on 2026-07-19 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0010_cliente_puntos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(blank=True, max_length=120)),
                ('cliente_telefono', models.CharField(blank=True, max_length=20)),
                ('cliente_email', models.EmailField(blank=True, max_length=254)),
                ('tipo', models.CharField(choices=[('TRATAMIENTO', 'Recordatorio de toma'), ('REPOSICION', 'Reposición de medicamento'), ('CITA', 'Cita / revisión')], default='TRATAMIENTO', max_length=15)),
                ('mensaje', models.TextField()),
                ('producto', models.CharField(blank=True, max_length=200)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('enviado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recordatorio',
                'verbose_name_plural': 'Recordatorios',
                'ordering': ['-creado'],
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='anulada',
            field=models.BooleanField(default=False, verbose_name='Anulada'),
        ),
        migrations.AddField(
            model_name='venta',
            name='receta_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='recetas/', verbose_name='Foto de receta'),
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('APERTURA', 'Apertura'), ('CIERRE', 'Cierre')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tarjeta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notas', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de caja',
                'verbose_name_plural': 'Arqueo de caja',
                'ordering': ['-fecha'],
            },
        ),
    ]
