# Generated by Django 5.0.1 on 2026-07-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0011_recordatorio_venta_anulada_venta_receta_imagen_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='fondo_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Fondo inicial'),
        ),
    ]
