# Generated by Django 5.0.1 on 2026-07-19 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0012_caja_fondo_inicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('SUGERIDO', 'Sugerido'), ('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido')], default='SUGERIDO', max_length=10)),
                ('notas', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='farmacia.proveedor')),
            ],
            options={
                'verbose_name': 'Pedido a proveedor',
                'verbose_name_plural': 'Pedidos a proveedores',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='LineaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_sugerida', models.IntegerField(default=0)),
                ('cantidad_pedida', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmacia.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='farmacia.pedidoproveedor')),
            ],
        ),
    ]
